name: E2E tests

on: [workflow_call]

permissions: read-all

jobs:
  e2e-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-node-install
        name: Install Node, pnpm and dependencies.
      - name: Install Cypress
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - uses: ./.github/actions/uv-python-install
        name: Install Python, uv and Python & pnpm (uv does it automatically) dependencies
        with:
          working-directory: ${{ env.BACKEND_DIR }}
          uv-args: --extra tests
      - name: Run tests
        run: pnpm test:e2e
        shell: bash
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always() && hashFiles('cypress/screenshots/**') != ''
        with:
          name: cypress-screenshots-${{ matrix.os }}
          path: cypress/screenshots
