name: Unit & integration tests

on: [workflow_call]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    name: python ${{ matrix.python-version }}
    env:
      BACKEND_DIR: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-node-install
        name: Install Node, pnpm and dependencies.
      - uses: ./.github/actions/uv-python-install
        name: Install Python, uv and Python dependencies
        with:
          python-version: ${{ matrix.python-version }}
          uv-args: --extra tests --extra custom-data
      - name: Run backend tests
        run: uv run --no-project pytest --cov=chainlit/
      - name: Run frontend tests
        run: pnpm run test
